name: finny
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.6.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
